{"name": "Тест невозможности авторизации пользователя с неверными данными", "status": "passed", "description": "Создаем запись пользователя передавая email, пароль и имя. Затем входим с заведомо неверными логином и паролем.Должны получить в ответе код: 401 и значение 'success': False", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'7368my_email_z8537@gmail.com'"}, {"name": "password", "value": "'Pass.2'"}], "start": 1714943607222, "stop": 1714943607605}], "parameters": [{"name": "data_change", "value": "'email'"}], "start": 1714943607222, "stop": 1714943607608, "uuid": "39adc1eb-5181-4fc4-a96c-ab3d74c80c6a", "historyId": "72dde406d67db7aa7c87a59b643eff32", "testCaseId": "50a14353b09352770312ed64e2c88143", "fullName": "tests.test_user.TestUser#test_user_authorization_with_incorrect_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "DESKTOP-BIKQ56D"}, {"name": "thread", "value": "1764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}